name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  scala-build:
    uses: ./.github/workflows/scala-build.yml

  build-pdf:
    uses: ./.github/workflows/build-pdf.yml

  release:
    needs: [scala-build, build-pdf]
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v5
        with:
          name: scalatro-jar
          path: ./release-assets

      - name: Download PDF
        uses: actions/download-artifact@v5
        with:
          name: report-pdf
          path: ./release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          files: |
            ./release-assets/*.jar
            ./release-assets/report.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
